sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - BUCKET=akerl-sns-to-slack
  - secure: YazW+88XHqn0fcKpol6+GkfrWEHD8BpMcxQAzmU59HBsRefjNOE43MqcldDiR0NmD/EvB24zcszrK+T4VpfIO0HPnAZjQ+YjFr/d+zTY1SGgPj7PTmLizKLwvcB9ON5OSNneWUPK9qor5SfWlU/6Bx5006pKPxywT5Zdl0ihEeUZeTTdZvbolJlgsSjHHqsi8HcEyj8N2f8YtfXlL/O+s24tR9NI6WX+oRlThISV2QivFHFHLQzVFjfABmIb91bEHnm9C6vvIh9IZDkSl0dgF1pkMF6BLmFI0UelDGpQhNBdbMo1NZeRWvGh1U3gZ5kkmkW63zGS+rMjtlf75cfBI0MoJdho7oE3F1ywt9tJ5r5lKUJnlkFnw1cl5Q1jmAg2x5EAomhMFTsKWTJRHLyjmZkQdPr9O755YbqZcM6jzchyWeTp//ZzfCWMi1ZVN4WzbrTFfsdLuUAjh5XocMK2K9i3AF1G+Cg0uwtmcNL0EjQQMoJ2mFjQNEb5Eh5+ZnmfP3v3J1AfFr0mqmqLYRKjuTapnjuw2gQTNmXyGNMNP4GgFrsIBwDKyBl7BgSQJT0xA+DqAiJsEwJ5wk6l7plm7K0b8fZDjXM3ypAnZTIDUOUEeaUBkjKARDzerqBB1WptRq5QrULNo9TPR/JNqzzatyzyxhpGPv6r75GbQKOYk0M=
  - secure: TmzdGu3YMf7ov7QcxB6PMWXdZa7LJXqG1JHRa1xSGel92eQz7swWCA5ZvOZLv/e8ApCfAnRGTDrviSRyOO4pXhWHAdSH/fzVJFzc/NBKK8y1t9EGqIFEMLc6UU7sCaFQYhYtFuEXilXEhxADswXI68RnLpYpemGCkax3B0NaT6Voj9qIZfgu3JhIerr/OPbFY2ydcZ9eu8ceV/hPrQ5iZYjCbKvyX6iquQy6Y5Zrh0IgXxWYoJ/VHH7CpnRN8R07dkvKdN4Pyz8YyDuSb2JzngntJ9Ad1pJLuBQT4QyPITTPLrcfAiRO08Fj1P3F8BZEb4/UlGKTrqeB9vpmEfRfjHU+G8pUEJoq6Q2hT4GVk0FkuPxqhosYMNwUV+vgggFSztID5dx5AYLT2Hstip6gqGT6Tp/opax/I9A57RHLUCPjhpfr0KpzstalUrOWA9E4lKqzJSEWAowsOUxpxP+rAGLZFkVG9+GxqBXFQSEAq49zPJd+dXi1SXvPoN38LhqhxIv2Qxyr9mv5j8Vq2tAJggIH79G47RZ5yECccvUD/aJfPAwiRGZmkddcV35dK2e6btBEyjqP+0iBQKAPw3GhppZkO1aIBdiH3a/SYPmGS2qgS0ufeAM8Wb6GFqXgsWOEcfduf2WuFnAbF4iR9Aqu3VOR8leY/HqbVOlP9UMF7Ac=
script: make
deploy:
  provider: script
  script:
  - make release || travis_terminate 1
  - aws s3 cp pkg/payload.zip "s3://$BUCKET/lambdas/payload-$TRAVIS_TAG.zip" || travis_terminate
    1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: CIWPjeq4MO5/24XqrZTd6u/OHl0OwQOklsJge2UnXVE2KtRLSemA+uvtSCtxTdyoer3TOEoQJ9nFbTp1mdeHqpNPMqhQ0lbn7usrPxWEnwVVmDi1/7tAgmrgt+upYPnXF5e5xPcmCWxuCGoPOKzKWVYpGlWeTiO7fcyDNfL0D3GQ8YuYjO+i144Nlk9aAFoSBe9V6eqsoU1AiTaBxW9dKTEMxRI1Bg1TT4VjcuzpWIuLp73GKA5Itbrr0Se3FUyFmkuynxCtivAb/SBQ2b6uKO8R/DG8I5G++HUohPiTNaZQDRcc2QRR1dBanwBHOKYEIEPRVaTaY1ncnMqWoLnduw05UL6iqE7AagLxl+3v+3rFin6omz4IhO6xtyivUzr6FmAgohbAeCBShDDZ60Bd4GcLGWlQsrcD9IfVIZE3sTh3t9a4PXguL+A6TFl6NvCBo+41Zjv75wvd+VbwwkTMNb7HXgmCBaP4WWsO1P492C1Aoah2yRhRpROELFhU/8ZnGhGPD4ii21Bx7Ou4P+fv2vQoWbIP0jbxqhvao2YR1cLLfqxY4k2BNn1wvvrkmLL5spXoQhYqgsSUUQkWHt02tzLM7iCTRHB5wLTmyLb5d5nbqfw9Ik5yYC1w+pMSI1f9r4KXYlSckHzY3JnvnCVHhNPpYtv2DMy1QQNtEx0L7h4=
